version: '3.8'

services:
  bot:
    #info
    container_name: bot
    image: leulshawell/bots:bot
    #build
    build:
      context: ./bot/
      dockerfile: Dockerfile
    depends_on:
       - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - WEB3_CLIENT_URI=http://web3:4444/api
    networks:
      - app-network

  web3:
    container_name: web3
    image: leulshawell/bots:web3
    build:
      context: ./web3_service/
      dockerfile: Dockerfile
    networks:
      - app-network
      
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db 

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
